# Generated by Django 2.0.1 on 2021-01-27 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='接口名称')),
                ('url', models.CharField(max_length=64, verbose_name='接口地址')),
                ('desc', models.CharField(max_length=1024, verbose_name='接口描述')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('desc', models.CharField(max_length=1024, verbose_name='项目描述')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='项目名称')),
                ('test_environment', models.CharField(blank=True, max_length=1024, verbose_name='测试环境')),
                ('dev_environment', models.CharField(blank=True, max_length=1024, verbose_name='开发环境')),
                ('online_environment', models.CharField(blank=True, max_length=1024, verbose_name='线上环境')),
                ('bak_environment', models.CharField(blank=True, max_length=1024, verbose_name='备用环境')),
                ('environment_type', models.CharField(max_length=1, verbose_name='环境标识')),
                ('principal', models.CharField(blank=True, max_length=16)),
                ('variables', models.CharField(max_length=2048, verbose_name='项目的公共变量')),
                ('headers', models.CharField(max_length=1024, verbose_name='项目的公共头部信息')),
                ('func_file', models.CharField(blank=True, max_length=64, verbose_name='函数文件')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('desc', models.CharField(max_length=1024, verbose_name='项目描述')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='interface_app.Project'),
        ),
        migrations.AddField(
            model_name='api',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='interface_app.Module'),
        ),
        migrations.AddField(
            model_name='api',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='interface_app.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('name', 'project')},
        ),
    ]
