# Generated by Django 2.2.2 on 2020-12-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='userid',
            new_name='user_id',
        ),
    ]
