# Generated by Django 2.0.1 on 2021-07-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestepdata',
            name='num',
            field=models.IntegerField(blank=True, verbose_name='接口序号'),
        ),
    ]
