# Generated by Django 2.0.1 on 2021-02-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='num',
        ),
    ]
