# Generated by Django 2.0.1 on 2020-12-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='func_file',
            field=models.CharField(blank=True, max_length=64, verbose_name='函数文件'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='项目名称'),
        ),
    ]
