# Generated by Django 2.0.1 on 2021-02-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='variable',
            new_name='body_form_data',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='json_variable',
            new_name='body_json',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='variable_type',
            new_name='body_type',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='param',
            new_name='url_param',
        ),
    ]
