# Generated by Django 2.2.2 on 2020-12-21 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024, verbose_name='项目描述'),
            preserve_default=False,
        ),
    ]
