# Generated by Django 2.0.1 on 2021-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_remove_api_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=128, verbose_name='接口名称'),
        ),
    ]
