# Generated by Django 2.2.2 on 2020-12-22 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_project_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='environment_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=1, verbose_name='环境标识'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='environment',
            field=models.CharField(max_length=1024, verbose_name='环境'),
        ),
    ]
