# Generated by Django 2.0.1 on 2021-01-28 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_auto_20210128_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
