# Generated by Django 2.2.2 on 2021-01-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_auto_20210124_2016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('name', 'project')},
        ),
    ]
