# Generated by Django 2.0.1 on 2021-02-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_auto_20210203_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='status_url',
            new_name='base_url',
        ),
    ]
