# Generated by Django 2.0.1 on 2021-01-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0003_auto_20210124_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_column='name', max_length=64, unique=True, verbose_name='项目名称'),
        ),
    ]
