# Generated by Django 2.0.1 on 2021-02-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0003_auto_20210204_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='url',
            field=models.CharField(max_length=256, verbose_name='接口地址'),
        ),
    ]
