# Generated by Django 2.0.1 on 2021-01-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0003_auto_20210128_2122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='api',
            unique_together=set(),
        ),
    ]
