# Generated by Django 2.0.1 on 2021-01-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0004_auto_20201223_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='environment',
        ),
        migrations.AddField(
            model_name='project',
            name='bak_environment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='备用环境'),
        ),
        migrations.AddField(
            model_name='project',
            name='dev_environment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='开发环境'),
        ),
        migrations.AddField(
            model_name='project',
            name='online_environment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='线上环境'),
        ),
        migrations.AddField(
            model_name='project',
            name='test_environment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='测试环境'),
        ),
    ]
