# Generated by Django 2.0.2 on 2021-06-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0005_auto_20210607_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case_set',
            new_name='CaseSet',
        ),
    ]
