# Generated by Django 2.0.1 on 2021-01-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0005_auto_20210128_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='api',
            unique_together={('name', 'module', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('name', 'project')},
        ),
    ]
