# Generated by Django 2.0.2 on 2021-06-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0006_auto_20210607_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='用例名称')),
                ('desc', models.CharField(blank=True, max_length=256, verbose_name='用例描述')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('case_set', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='interface_app.CaseSet')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_diff', to='interface_app.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('name', 'case_set', 'project')},
        ),
    ]
