# Generated by Django 2.2.2 on 2021-01-09 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0007_auto_20210109_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024, verbose_name='接口描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='接口地址'),
            preserve_default=False,
        ),
    ]
