# Generated by Django 2.0.1 on 2021-01-29 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0007_api_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='params',
            field=models.CharField(default=django.utils.timezone.now, max_length=2048, verbose_name='请求参数'),
            preserve_default=False,
        ),
    ]
