# Generated by Django 2.0.2 on 2021-06-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0007_auto_20210607_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_diff2', to='interface_app.Project'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_diff4', to='interface_app.Project'),
        ),
        migrations.AlterField(
            model_name='caseset',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_diff3', to='interface_app.Project'),
        ),
        migrations.AlterField(
            model_name='module',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_diff1', to='interface_app.Project'),
        ),
    ]
