# Generated by Django 2.0.1 on 2021-01-29 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0008_api_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='params',
        ),
        migrations.AddField(
            model_name='api',
            name='json_variable',
            field=models.CharField(default=django.utils.timezone.now, max_length=2048, verbose_name='请求json参数'),
            preserve_default=False,
        ),
    ]
