# Generated by Django 2.2.2 on 2021-01-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0008_auto_20210109_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='porject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='interface_app.Project'),
        ),
    ]
