# Generated by Django 2.2.2 on 2021-01-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0009_api_porject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='porject',
            new_name='project',
        ),
    ]
