# Generated by Django 2.0.1 on 2021-01-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0010_auto_20210109_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
    ]
