# Generated by Django 2.0.1 on 2021-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0011_auto_20210122_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='desc',
            field=models.CharField(default='', max_length=1024, verbose_name='项目描述'),
            preserve_default=False,
        ),
    ]
