# Generated by Django 2.0.2 on 2021-06-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0012_auto_20210617_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_set',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='interface_app.CaseSet'),
        ),
    ]
