# Generated by Django 2.0.2 on 2021-06-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0014_auto_20210624_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedata',
            name='case',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='interface_app.Case'),
        ),
    ]
