# Generated by Django 2.0.2 on 2021-06-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0015_auto_20210625_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='interface_app.CaseSet'),
        ),
    ]
