# Generated by Django 2.0.2 on 2021-06-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0016_auto_20210626_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseData',
            new_name='CaseStepData',
        ),
    ]
