# Generated by Django 2.0.2 on 2021-06-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0019_auto_20210626_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestepdata',
            name='case',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='interface_app.Case'),
        ),
    ]
